spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: 2071514@hansung.ac.kr
    password: pavyitlhipqtmbel
    properties:
      mail:
        smtp:
          starttls:
            enable: true
            required: true
          auth: true
          timeout: 5000

  datasource:
    master:
      jdbc-url: jdbc:mariadb://192.168.201.29:3306/idus_exam
      driver-class-name: org.mariadb.jdbc.Driver
      username: kjg
      password: qwer1234
    slave:
      jdbc-url: jdbc:mariadb://192.168.201.30:3306/idus_exam
      driver-class-name: org.mariadb.jdbc.Driver
      username: kjg
      password: qwer1234
  jpa:
    database-platform: org.hibernate.dialect.MariaDBDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace
    org.hibernate.type.descriptor.sql: trace